# Generated by Django 5.0.3 on 2024-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userdeco_nickname_alter_userdeco_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdeco',
            name='nickname',
        ),
        migrations.AddField(
            model_name='userdeco',
            name='text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userdeco',
            name='avatar',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
